# Site settings
title: Wiggins Watch
email: 22wigginswatch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  News, views and opinions on Andrew Wiggins and other sports topics. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.wigginswatch.com" # the base hostname & protocol for your site
twitter_username: 22wigginswatch


# Build settings
markdown: kramdown
